[project]
name = "pytriton-serve-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "flagembedding>=1.3.5",
    "nvidia-pytriton>=0.7.0",
    "pydantic>=2.12.4",
]
